name: balanced_news
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  sizer: ^2.0.15
  google_fonts: ^2.3.1
  google_nav_bar: ^5.0.5
  card_swiper: ^2.0.1
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  webview_flutter: ^3.0.1
  cloud_firestore: ^3.1.13
  firebase_auth: ^3.3.15
  google_sign_in: ^5.3.0
  equatable: ^2.0.3
  firebase_core: ^1.15.0
  flutter_svg: ^1.0.3
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/svg/



